<template>
  <section class="workbench-panel">
    <div class="panel-title">
      <p>Step 02</p>
      <h2>Prepare simulation environment</h2>
      <span :class="['status', isReady ? 'ready' : 'processing']">{{ isReady ? 'Ready' : 'Processing' }}</span>
    </div>

    <div class="summary-grid">
      <article>
        <span>Project</span>
        <strong>{{ projectData?.project_id || 'Unknown' }}</strong>
      </article>
      <article>
        <span>Simulation</span>
        <strong>{{ simulationId || 'Creating...' }}</strong>
      </article>
      <article>
        <span>Agents</span>
        <strong>{{ profiles.length || expectedTotal || '-' }}</strong>
      </article>
      <article>
        <span>Progress</span>
        <strong>{{ prepareProgress }}%</strong>
      </article>
    </div>

    <div class="progress-card">
      <h3>{{ headline }}</h3>
      <p>{{ progressMessage || 'Orion is creating the simulation record and preparing agent profiles.' }}</p>
      <div class="progress-track">
        <span :style="{ width: `${progressBarValue}%` }"></span>
      </div>
    </div>

    <div v-if="profiles.length" class="preview-card">
      <h3>Agent preview</h3>
      <div class="agent-list">
        <button v-for="profile in profiles.slice(0, 8)" :key="profile.agent_id || profile.username" @click="selectedProfile = profile">
          <strong>{{ profile.name || profile.username || `Agent ${profile.agent_id}` }}</strong>
          <span>{{ profile.profession || profile.entity_type || 'Generated profile' }}</span>
        </button>
      </div>
    </div>

    <div v-if="simulationConfig" class="preview-card">
      <h3>Configuration</h3>
      <dl>
        <div>
          <dt>Auto rounds</dt>
          <dd>{{ autoGeneratedRounds || '-' }}</dd>
        </div>
        <div>
          <dt>Platforms</dt>
          <dd>{{ platformSummary }}</dd>
        </div>
      </dl>
    </div>

    <label class="rounds-control">
      <input type="checkbox" v-model="useCustomRounds" />
      <span>Use custom round count</span>
    </label>
    <input
      v-if="useCustomRounds"
      class="rounds-input"
      type="number"
      min="1"
      max="500"
      v-model.number="customMaxRounds"
    />

    <div class="actions">
      <button class="secondary-action" @click="$emit('go-back')">Back</button>
      <button class="primary-action" :disabled="!isReady" @click="handleStartSimulation">Start simulation</button>
    </div>

    <div v-if="selectedProfile" class="profile-modal" @click.self="selectedProfile = null">
      <article>
        <button class="close" @click="selectedProfile = null">Close</button>
        <h3>{{ selectedProfile.name || selectedProfile.username }}</h3>
        <p>{{ selectedProfile.bio || selectedProfile.description || 'No biography was returned for this profile.' }}</p>
      </article>
    </div>
  </section>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'
import {
  createSimulation,
  prepareSimulation,
  getPrepareStatus,
  getSimulationProfilesRealtime,
  getSimulationConfigRealtime
} from '../api/simulation'

const props = defineProps({
  projectData: Object,
  graphData: Object,
  systemLogs: Array
})

const emit = defineEmits(['go-back', 'next-step', 'add-log', 'update-status'])

const simulationId = ref(null)
const taskId = ref(null)
const prepareProgress = ref(0)
const progressMessage = ref('')
const profiles = ref([])
const expectedTotal = ref(null)
const simulationConfig = ref(null)
const selectedProfile = ref(null)
const useCustomRounds = ref(false)
const customMaxRounds = ref(40)
const isReady = ref(false)

let pollTimer = null
let profilesTimer = null
let configTimer = null

const addLog = (message) => emit('add-log', message)

const headline = computed(() => {
  if (isReady.value) return 'Environment is ready'
  if (simulationId.value) return 'Preparing agents and configuration'
  return 'Creating simulation'
})

const progressBarValue = computed(() => isReady.value ? 100 : Math.max(prepareProgress.value, simulationId.value ? 20 : 8))

const autoGeneratedRounds = computed(() => {
  const timeConfig = simulationConfig.value?.time_config
  if (!timeConfig?.total_simulation_hours || !timeConfig?.minutes_per_round) return null
  return Math.floor((timeConfig.total_simulation_hours * 60) / timeConfig.minutes_per_round)
})

const platformSummary = computed(() => {
  const config = simulationConfig.value || {}
  const platforms = []
  if (config.twitter_config) platforms.push('Twitter')
  if (config.reddit_config) platforms.push('Reddit')
  return platforms.length ? platforms.join(', ') : 'Default'
})

const handleStartSimulation = () => {
  const params = {}
  params.simulationId = simulationId.value
  if (useCustomRounds.value) {
    params.maxRounds = customMaxRounds.value
  }
  emit('next-step', params)
}

const createAndPrepare = async () => {
  if (!props.projectData?.project_id) {
    addLog('Project data is missing. Cannot create simulation.')
    emit('update-status', 'error')
    return
  }

  try {
    emit('update-status', 'processing')
    addLog('Creating simulation record...')
    const createRes = await createSimulation({
      project_id: props.projectData.project_id,
      graph_id: props.projectData.graph_id,
      enable_twitter: true,
      enable_reddit: true
    })

    if (!createRes.success) {
      throw new Error(createRes.error || 'Simulation creation failed')
    }

    simulationId.value = createRes.data.simulation_id
    addLog(`Simulation created: ${simulationId.value}`)

    const prepareRes = await prepareSimulation({
      simulation_id: simulationId.value,
      use_llm_for_profiles: true,
      parallel_profile_count: 5
    })

    if (!prepareRes.success) {
      throw new Error(prepareRes.error || 'Environment preparation failed')
    }

    if (prepareRes.data?.already_prepared) {
      addLog('Existing prepared environment found.')
      await loadPreparedData()
      return
    }

    taskId.value = prepareRes.data?.task_id
    expectedTotal.value = prepareRes.data?.expected_entities_count || null
    addLog(`Preparation task started: ${taskId.value || 'background task'}`)

    startPolling()
    startProfilesPolling()
    startConfigPolling()
  } catch (error) {
    addLog(`Environment setup failed: ${error.message}`)
    emit('update-status', 'error')
  }
}

const pollPrepareStatus = async () => {
  if (!simulationId.value) return
  try {
    const res = await getPrepareStatus({ task_id: taskId.value, simulation_id: simulationId.value })
    if (!res.success || !res.data) return

    prepareProgress.value = res.data.progress || prepareProgress.value
    progressMessage.value = res.data.message || progressMessage.value

    if (['completed', 'ready'].includes(res.data.status) || res.data.already_prepared) {
      addLog('Environment preparation completed.')
      await loadPreparedData()
    } else if (res.data.status === 'failed') {
      throw new Error(res.data.error || 'Preparation failed')
    }
  } catch (error) {
    addLog(`Preparation polling failed: ${error.message}`)
    stopAllPolling()
    emit('update-status', 'error')
  }
}

const fetchProfilesRealtime = async () => {
  if (!simulationId.value) return
  try {
    const res = await getSimulationProfilesRealtime(simulationId.value, 'reddit')
    if (res.success && res.data) {
      profiles.value = res.data.profiles || []
      expectedTotal.value = res.data.total_expected || expectedTotal.value
    }
  } catch (error) {
    console.warn('Failed to fetch profiles:', error)
  }
}

const fetchConfigRealtime = async () => {
  if (!simulationId.value) return
  try {
    const res = await getSimulationConfigRealtime(simulationId.value)
    if (res.success && res.data?.config_generated && res.data.config) {
      simulationConfig.value = res.data.config
      isReady.value = true
      prepareProgress.value = 100
      emit('update-status', 'completed')
      stopAllPolling()
    }
  } catch (error) {
    console.warn('Failed to fetch simulation config:', error)
  }
}

const loadPreparedData = async () => {
  await fetchProfilesRealtime()
  await fetchConfigRealtime()
  if (!simulationConfig.value) {
    startConfigPolling()
  }
}

const startPolling = () => {
  stopPolling()
  pollTimer = setInterval(pollPrepareStatus, 2000)
  pollPrepareStatus()
}

const startProfilesPolling = () => {
  stopProfilesPolling()
  profilesTimer = setInterval(fetchProfilesRealtime, 3000)
  fetchProfilesRealtime()
}

const startConfigPolling = () => {
  if (configTimer) return
  configTimer = setInterval(fetchConfigRealtime, 2500)
  fetchConfigRealtime()
}

const stopPolling = () => {
  if (pollTimer) clearInterval(pollTimer)
  pollTimer = null
}

const stopProfilesPolling = () => {
  if (profilesTimer) clearInterval(profilesTimer)
  profilesTimer = null
}

const stopConfigPolling = () => {
  if (configTimer) clearInterval(configTimer)
  configTimer = null
}

const stopAllPolling = () => {
  stopPolling()
  stopProfilesPolling()
  stopConfigPolling()
}

onMounted(createAndPrepare)
onUnmounted(stopAllPolling)
</script>

<style scoped>
.workbench-panel {
  height: 100%;
  overflow-y: auto;
  padding: 28px;
  background: #fffdf8;
}

.panel-title {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 8px 16px;
  align-items: start;
  margin-bottom: 22px;
}

.panel-title p {
  grid-column: 1 / -1;
  color: #8f5b2f;
  font-size: 12px;
  font-weight: 900;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.panel-title h2 {
  margin: 0;
  font-size: 30px;
}

.status {
  border-radius: 999px;
  padding: 8px 10px;
  font-weight: 900;
  font-size: 12px;
  background: #fff0cb;
  color: #85620c;
}

.status.ready {
  background: #d7eadb;
  color: #246333;
}

.summary-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}

.summary-grid article,
.progress-card,
.preview-card {
  border: 1px solid rgba(23, 32, 26, 0.12);
  border-radius: 8px;
  background: white;
  padding: 16px;
}

.summary-grid span {
  display: block;
  color: #69756b;
  font-size: 12px;
  font-weight: 800;
  margin-bottom: 8px;
}

.summary-grid strong {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.progress-card,
.preview-card {
  margin-top: 14px;
}

.progress-card h3,
.preview-card h3 {
  margin: 0 0 8px;
}

.progress-card p {
  color: #5c685e;
  line-height: 1.5;
}

.progress-track {
  height: 10px;
  border-radius: 999px;
  background: #eee8dd;
  overflow: hidden;
  margin-top: 16px;
}

.progress-track span {
  display: block;
  height: 100%;
  border-radius: inherit;
  background: #8f5b2f;
  transition: width 0.3s ease;
}

.agent-list {
  display: grid;
  gap: 8px;
}

.agent-list button {
  text-align: left;
  border: 1px solid rgba(23, 32, 26, 0.12);
  border-radius: 6px;
  background: #fffdf8;
  padding: 10px;
  cursor: pointer;
}

.agent-list strong,
.agent-list span {
  display: block;
}

.agent-list span {
  color: #69756b;
  font-size: 13px;
  margin-top: 4px;
}

dl {
  display: grid;
  gap: 10px;
}

dl div {
  display: flex;
  justify-content: space-between;
  gap: 16px;
}

dt {
  color: #69756b;
  font-weight: 800;
}

dd {
  margin: 0;
}

.rounds-control {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-top: 16px;
  font-weight: 800;
}

.rounds-input {
  width: 100%;
  margin-top: 10px;
  border: 1px solid rgba(23, 32, 26, 0.16);
  border-radius: 8px;
  padding: 12px;
  font: inherit;
}

.actions {
  display: grid;
  grid-template-columns: 1fr 2fr;
  gap: 10px;
  margin-top: 16px;
}

.primary-action,
.secondary-action {
  border-radius: 8px;
  padding: 15px;
  font-weight: 900;
  cursor: pointer;
}

.primary-action {
  border: 0;
  background: #17201a;
  color: white;
}

.primary-action:disabled {
  background: #d9d3c7;
  color: #777064;
  cursor: not-allowed;
}

.secondary-action {
  border: 1px solid rgba(23, 32, 26, 0.16);
  background: white;
  color: #17201a;
}

.profile-modal {
  position: fixed;
  inset: 0;
  display: grid;
  place-items: center;
  background: rgba(23, 32, 26, 0.34);
  padding: 20px;
  z-index: 100;
}

.profile-modal article {
  width: min(520px, 100%);
  background: #fffdf8;
  border-radius: 8px;
  padding: 22px;
}

.profile-modal p {
  color: #5c685e;
  line-height: 1.6;
}

.close {
  float: right;
  border: 0;
  background: transparent;
  font-weight: 900;
  cursor: pointer;
}
</style>
